name: Deployment

on:
  push:
    tags:
      - '*'

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Push Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: jerome1337/jeromepogeant.com
          tags: latest
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
